import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import profilePic from '../../public/images/profile/tangerine.png'
//import profilePic from '../../public/images/profile/developer-pic-1.png'
import AnimatedText from '@/components/AnimatedText'
import { LinkArrow } from '@/components/Icons'


export default function Home() {
  return (
    <>
      <Head>
        <title>Personal Website</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen dark:text-light'>
        <Layout className='pt-0'>
          <div className='flex items-center justify-between w-full'>
            <div className='w-1/4'>
              <Image src={profilePic} alt='profile' className='w-full h-auto'
              priority
              sizes='(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw'></Image>
            </div>
            <div className='w-1/2 flex flex-col items-center self-center'>
              <AnimatedText text='Hello, I am Giovanni.' className='!text-6xl !text-left'/>
              <p className='my-4 text-base font-medium'>
                Artificial Intelligence Researcher.
              </p>
              <div className='flex items-center self-start mt-2'>
                <Link href='/CV.pdf' target={'_blank'}
                className='flex items-center bg-dark text-light p-2.5 px-6
                rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                border-2 border-solid border-transparent hover:border-dark 
                dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light'
                >Resume <LinkArrow className={'w-6 ml-1'}/>
                </Link>
                <Link href='mailto:giovanni.scialla1808@outlook.it' target={'_blank'}
                className='ml-4 text-lg font-medium capitalize text-dark underline dark:text-light'
                >Contact</Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}
